istedad/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index, name="index"),
    path("haqqimizda", views.haqqimizda, name="haqqimizda"),
    path("struktur", views.struktur, name="struktur"),
    path("filiallar", views.filiallar, name="filiallar"),
    path("muellimler", views.muellimler, name="muellimler"),
    path("kurslar", views.kurslar, name="kurslar"),
    path("kurs_details/<slug:slug>", views.kurs_details, name="kurs_details"),
    path("xeber_details/<slug:slug>", views.xeber_details, name="xeber_details"),
    path("sinaq_details/<int:id>", views.sinaq_details, name="sinaq_details"),
    path("tedbirler", views.tedbirler, name="tedbirler"),
    path("qeydiyyatt", views.qeydiyyatt, name="qeydiyyat"),
    path("sinaqnetice", views.sinaqlar, name="sinaqnetice"),
    path("sinaqcavab", views.sinaqcavab, name="sinaqcavab"),
    path("adminsinaqcavab", views.adminsinaqcavab, name="adminsinaqcavab"),
]

istedadapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('istedad.urls')),
    path('', include('qeydiyyat.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qeydiyyat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("qeydiyyat", views.qeydiyyat, name="qeydiyyat"),
    path("sinaqqeydiyyat", views.sinaqqeydiyyat, name="sinaqqeydiyyat"),
    path("elaqe", views.elaqe, name="elaqe"),
]

qeydiyyat/models.py
from django.db import models

class AdminQeydiyyatForm(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    telNo_basliq = models.CharField(null=True, max_length=50)
    telNo = models.CharField(max_length=50)
    rayon = models.CharField(max_length=50)
    mekteb = models.CharField(max_length=50)
    sinif = models.CharField(max_length=50)
    blok = models.CharField(max_length=50)
    xdil = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.fname}"
    
class AdminSinaqQeydiyyatForm(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    telNo_basliq = models.CharField(null=True, max_length=50)
    telNo = models.CharField(max_length=50)
    rayon = models.CharField(max_length=50)
    mekteb = models.CharField(max_length=50)
    sinif = models.CharField(max_length=50)
    blok = models.CharField(max_length=50)
    xdil = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.fname}"
    
class AdminElaqeForm(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    telNo = models.CharField(max_length=50)
    subject = models.CharField(max_length=500)
    message = models.CharField(max_length=1500)

    def __str__(self):
        return f"{self.fname}"

qeydiyyat/forms.py
from django.forms import ModelForm
from . models import AdminQeydiyyatForm, AdminSinaqQeydiyyatForm, AdminElaqeForm

class QeydiyyatForm(ModelForm):
    class Meta:
        model = AdminQeydiyyatForm
        fields = '__all__'

class SinaqQeydiyyatForm(ModelForm):
    class Meta:
        model = AdminSinaqQeydiyyatForm
        fields = '__all__'

class ElaqeForm(ModelForm):
    class Meta:
        model = AdminElaqeForm
        fields = '__all__'

qeydiyyat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .forms import QeydiyyatForm, SinaqQeydiyyatForm, ElaqeForm


def qeydiyyat(request):
    form = QeydiyyatForm()
    
    if request.method == 'POST':
        form = QeydiyyatForm(request.POST)
        
        if form.is_valid():
            form.save()
    
    context = {'form': form}
    return render(request, 'qeydiyyat/qeydiyyat.html', context)

def sinaqqeydiyyat(request):
    form = SinaqQeydiyyatForm()

    if request.method == 'POST':
        form = SinaqQeydiyyatForm(request.POST)

        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'qeydiyyat/sinaqqeydiyyat.html', context)

def elaqe(request):
    form = ElaqeForm()

    if request.method == 'POST':
        form = ElaqeForm(request.POST)

        if form.is_valid():
            form.save()
    context = {'form':form}
    return render(request, 'qeydiyyat/elaqe.html', context)

qeydiyyat/templates/qeydiyyat/elaqe.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Əsas səhifə {% endblock %}

{% block content %}

	<div id="fh5co-contact">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-md-push-1 animate-box">
					
					<div class="fh5co-contact-info">
						<h3>Əlaqə məlumatları</h3>
						<ul>
							<li class="address">Nəsrəddin Tusi küçəsi<br>Lifan zavod ilə üzbəüz</li>
							<li class="phone"><a href="tel://+994365457411">036 545 74 11 Qeydiyyat şöbəsi</a></li>
							<li class="phone"><a href="tel://+994703057411">070 305 74 11 Tədris şöbəsi</a></li>
							<li class="phone"><a href="tel://+994773457411">077 345 74 11 Mühasibatlıq</a></li>
							<li class="email"><a href="istedad21@gmail.com">www.istedad21.edu.az</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-6 animate-box">
					<h3>Əlaqə yarat!</h3>
					<form action="elaqe" method="POST">
						{% csrf_token %}
						<div class="row form-group">
							<div class="col-md-6">
								<input type="text" name="fname" maxlength="50" class="form-control" placeholder="Adınız" required id="id_fname">
							</div>
							<div class="col-md-6">
								<input type="text" name="lname" maxlength="50" class="form-control" placeholder="Soyadınız" required id="id_lname">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<input type="text" name="telNo" maxlength="50" class="form-control" placeholder="Telefon No" required id="id_telNo">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<input type="text" name="subject" maxlength="500" class="form-control" placeholder="Mövzu" required id="id_subject">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<input type="textarea" name="message" maxlength="1500" cols="30" rows="10" class="form-control" placeholder="Bizə yazın"  required id="id_message">
							</div>
						</div>
						<div class="form-group">
							<input type="submit" value="Mesaj göndər" class="btn btn-success">
						</div>
					</form>		
				</div>
			</div>
			
		</div>
	</div>
	<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d943.1315332830261!2d45.42416846379399!3d39.195118962262256!3m2!1i1024!2i768!4f13.1!5e1!3m2!1str!2s!4v1624440346317!5m2!1str!2s" width="2000" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
{% endblock %}

qeydiyyat/templates/qeydiyyat/qeydiyyat.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Kursa qeydiyyat {% endblock %}

{% block content %}


	<div id="fh5co-pricing" class="fh5co-bg-section">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>ONLINE QEYDİYYAT</h2>
					<p>İstedad kurslarının müxtəlif tədris növlərinə və sınaqlarına online olaraq qeydiyyatdan keçə bilərsiniz.</p>
				</div>

				<div class="col-md-6 animate-box"><h3>Qeydiyyatdan keç!</h3>
					<form action="qeydiyyat" method="POST">
						{% csrf_token %}
						<div class="row form-group">
							<div class="col-md-6">
								<input type="text" name="fname" maxlength="50" class="form-control" placeholder="Adınız" required id="id_fname">
							</div>
							<div class="col-md-6">
								<input type="text" name="lname" maxlength="50" class="form-control" placeholder="Soyadınız" required id="id_lname">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-3">
								<p class="form-control">+994</p>
							</div>
							<div class="col-md-3">
								<select name="telNo_basliq" maxlength="50" class="form-control" maxlength="50" required id="id_telNo_basliq">
									<option value="36">036</option>
									<option value="50">050</option>
									<option value="51">051</option>
									<option value="10">010</option>
									<option value="55">055</option>
									<option value="99">099</option>
									<option value="70">070</option>
									<option value="77">077</option>
									<option value="60">060</option>
								</select>
							</div>
							
							<div class="col-md-6">
								<input type="text" name="telNo" maxlength="50" class="form-control" placeholder="Telefon No" required id="id_telNo">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-6">
								<select name="rayon" maxlength="50" class="form-control" maxlength="50" required id="id_rayon" placeholder="Rayon">
									<option value="1">Naxçıvan şəhəri</option>
									<option value="2">Babək rayon</option>
									<option value="3">Culfa rayon</option>
									<option value="4">Ordubad rayon</option>
									<option value="4">Şahbuz rayon</option>
									<option value="4">Kəngərli rayon</option>
									<option value="4">Şərur rayon</option>
									<option value="4">Sədərək rayon</option>
								</select>
							</div>
							<div class="col-md-6">
								<input type="text" name="mekteb" maxlength="50" class="form-control" placeholder="Məktəb" required id="id_mekteb">
							</div>
						</div>
						
						<div class="row form-group">
							<div class="col-md-6">
								<select name="sinif" maxlength="50" class="form-control" maxlength="50" required id="id_sinif" placeholder="Sinif">
									<option value="9">9-cu sinif</option>
									<option value="10">10-cu sinif</option>
									<option value="11">11-ci sinif</option>
								</select>
							</div>
							<div class="col-md-6">
								<select name="blok" maxlength="50" class="form-control" maxlength="50" required id="id_blok" placeholder="Blok">
									<option value="1">I blok</option>
									<option value="2">II blok</option>
									<option value="3">III blok</option>
									<option value="4">IV blok</option>
								</select>
							</div>
						</div>
						
						<div class="row form-group">
							<div class="col-md-12">
								<select name="xdil" class="form-control" maxlength="50" required id="id_xdil">
									<option value="İngilis dili">İngilis dili</option>
									<option value="Rus dili">Rus dili</option>
									<option value="Fransız dili">Fransız dili</option>
									<option value="Alman dili">Alman dili</option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<input type="submit" value="Qeydiyyatdan Keç" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

qeydiyyat/templates/qeydiyyat/sinaqqeydiyyat.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Sınaq qeydiyyat {% endblock %}

{% block content %}

	<div id="fh5co-pricing" class="fh5co-bg-section">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>ONLINE QEYDİYYAT</h2>
					<p>İstedad kurslarının sınaqlarına online olaraq qeydiyyatdan keçə bilərsiniz.</p>
				</div>

				<div class="col-md-6 animate-box"><h3>Qeydiyyatdan keç!</h3>
					<form action="sinaqqeydiyyat" method="POST">
						{% csrf_token %}
						<div class="row form-group">
							<div class="col-md-6">
								<input type="text" name="fname" maxlength="50" class="form-control" placeholder="Adınız" required id="id_fname">
							</div>
							<div class="col-md-6">
								<input type="text" name="lname" maxlength="50" class="form-control" placeholder="Soyadınız" required id="id_lname">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-3">
								<p class="form-control">+994</p>
							</div>
							<div class="col-md-3">
								<select name="telNo_basliq" maxlength="50" class="form-control" maxlength="50" required id="id_telNo_basliq">
									<option value="36">036</option>
									<option value="50">050</option>
									<option value="51">051</option>
									<option value="10">010</option>
									<option value="55">055</option>
									<option value="99">099</option>
									<option value="70">070</option>
									<option value="77">077</option>
									<option value="60">060</option>
								</select>
							</div>
							
							<div class="col-md-6">
								<input type="text" name="telNo" maxlength="50" class="form-control" placeholder="Telefon No" required id="id_telNo">
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-6">
								<select name="rayon" maxlength="50" class="form-control" maxlength="50" required id="id_rayon" placeholder="Rayon">
									<option value="1">Naxçıvan şəhəri</option>
									<option value="2">Babək rayon</option>
									<option value="3">Culfa rayon</option>
									<option value="4">Ordubad rayon</option>
									<option value="4">Şahbuz rayon</option>
									<option value="4">Kəngərli rayon</option>
									<option value="4">Şərur rayon</option>
									<option value="4">Sədərək rayon</option>
								</select>
							</div>
							<div class="col-md-6">
								<input type="text" name="mekteb" maxlength="50" class="form-control" placeholder="Məktəb" required id="id_mekteb">
							</div>
						</div>
						
						<div class="row form-group">
							<div class="col-md-6">
								<select name="sinif" maxlength="50" class="form-control" maxlength="50" required id="id_sinif" placeholder="Sinif">
									<option value="9">9-cu sinif</option>
									<option value="10">10-cu sinif</option>
									<option value="11">11-ci sinif</option>
								</select>
							</div>
							<div class="col-md-6">
								<select name="blok" maxlength="50" class="form-control" maxlength="50" required id="id_blok" placeholder="Blok">
									<option value="1">I blok</option>
									<option value="2">II blok</option>
									<option value="3">III blok</option>
									<option value="4">IV blok</option>
									<option value="5">V blok</option>
								</select>
							</div>
						</div>
						
						<div class="row form-group">
							<div class="col-md-12">
								<select name="xdil" class="form-control" maxlength="50" required id="id_xdil">
									<option value="İngilis dili">İngilis dili</option>
									<option value="Rus dili">Rus dili</option>
									<option value="Fransız dili">Fransız dili</option>
									<option value="Alman dili">Alman dili</option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<input type="submit" value="Qeydiyyatdan Keç" class="btn btn-success">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}