istedad/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index, name="index"),
    path("haqqimizda", views.haqqimizda, name="haqqimizda"),
    path("struktur", views.struktur, name="struktur"),
    path("filiallar", views.filiallar, name="filiallar"),
    path("muellimler", views.muellimler, name="muellimler"),
    path("kurslar", views.kurslar, name="kurslar"),
    path("kurs_details/<slug:slug>", views.kurs_details, name="kurs_details"),
    path("xeber_details/<slug:slug>", views.xeber_details, name="xeber_details"),
    path("sinaq_details/<int:id>", views.sinaq_details, name="sinaq_details"),
    path("tedbirler", views.tedbirler, name="tedbirler"),
    path("qeydiyyatt", views.qeydiyyatt, name="qeydiyyat"),
    path("sinaqnetice", views.sinaqlar, name="sinaqnetice"),
    path("sinaqcavab", views.sinaqcavab, name="sinaqcavab"),
    path("adminsinaqcavab", views.adminsinaqcavab, name="adminsinaqcavab"),
]

istedadapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('istedad.urls')),
    path('', include('qeydiyyat.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

istedad/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.utils.html import mark_safe
from . import custom_static_func

sinaqmodel = (
    ("asagisinif", "Aşağı siniflər"),
    ("blok9_10", "Blok 9 və 10-cu siniflər"),
    ("blok11", "Blok 11-ci sinif"),
    ("buraxilis9", "Buraxılış 9-cu sinif"),
    ("buraxilis10", "Buraxılış 10"),
    ("buraxilis11", "Buraxılış 11"),
)


class EsasSehife(models.Model):
    basliq = RichTextField(blank=True, max_length=200)
    elave = RichTextField(blank=True, max_length=100)
    elave1 = RichTextField(blank=True, max_length=100)
    sekil = models.ImageField(null=False, upload_to="istedad_images/giris/")
    is_active = models.BooleanField()

    def __str__(self):
        return f"{self.elave}"


class Saygac(models.Model):
    basliq = models.CharField(max_length=50)
    cem = models.IntegerField()
    suret = models.IntegerField()
    interval = models.IntegerField()
    icon = models.CharField(max_length=50, null=True)
    is_active = models.BooleanField()

    def __str__(self):
        return f"{self.basliq}"


class Struktur(models.Model):
    vezife = models.CharField(max_length=50)
    ad_soyad = models.CharField(max_length=50)
    elave = models.CharField(max_length=100)
    sekil = models.ImageField(null=False, upload_to="istedad_images/struktur/")
    is_active = models.BooleanField()

    def __str__(self):
        return f"{self.ad_soyad}"


class Muellim(models.Model):
    ad = models.CharField(max_length=50)
    fenn = models.CharField(max_length=50)
    aciqlama = RichTextField(blank=True)
    sekil = models.ImageField(upload_to="istedad_images/muellim/")
    is_active = models.BooleanField()
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True, editable=False)

    def __str__(self):
        return f"{self.ad}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.ad)
        super().save(*args, **kwargs)


class Kurslar(models.Model):
    kurs_adi = models.CharField(max_length=50)
    genis_melumat = RichTextField()
    is_active = models.BooleanField()
    sekil = models.ImageField(upload_to="istedad_images/kurslar/")
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True, editable=False)

    def __str__(self):
        return f"{self.kurs_adi}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.kurs_adi)
        super().save(*args, **kwargs)


class Tedbirler(models.Model):
    tarix = models.DateField(auto_now_add=True)
    basliq = models.CharField(max_length=100)
    sekil = models.ImageField(upload_to="istedad_images/xeberler/")
    aciqlama = RichTextField()
    is_active = models.BooleanField()
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True, editable=False)

    def __str__(self):
        return f"{self.basliq}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.basliq)
        super().save(*args, **kwargs)


class Serhler(models.Model):
    ad_soyad = models.CharField(max_length=50)
    yuksek_netice = models.CharField(max_length=50)
    basliq = models.CharField(max_length=100)
    aciqlama = models.TextField()
    sekil = models.ImageField(null=True, upload_to="istedad_images/serhler/")
    is_active = models.BooleanField()
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True, editable=False)

    def __str__(self):
        return f"{self.ad_soyad}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.ad_soyad)
        super().save(*args, **kwargs)


class Media(models.Model):
    sekil_adi = models.CharField(max_length=50, blank=True)
    sekil = models.ImageField(upload_to="istedad_images/media/")
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.sekil_adi}"

    def sekilgoster(self):  # new
        return mark_safe(f'<img src = "{self.sekil.url}" width = "300"/>')


class Sinaqlar(models.Model):
    sinaq_adi = models.CharField(max_length=50, verbose_name="Sınaq adı")
    sinaq_tarix = models.DateField(auto_now_add=True)
    sinaq_nov = models.CharField(choices=sinaqmodel, max_length=100, null=True)
    sinaq_duzgun_cvb = models.TextField(blank=True, null=True)
    sinaq_sagird_cvb = models.TextField(blank=True, null=True)
    sinaq_sekil = models.ImageField(upload_to="istedad_images/sinaq/", null=True)
    is_active = models.BooleanField()
    counter = models.IntegerField(default=0)

    letter_replacements = [('c', 'Ç'), ('e', 'Ə'), ('g', 'Ğ'), ('i', 'İ'), ('o', 'Ö'), ('s', "Ş"), ('u', 'Ü')]

    @staticmethod
    def replace_letters(input_str, replacements):
        for old_char, new_char in replacements:
            input_str = input_str.replace(old_char, new_char)
        return input_str

    def hesabla(self):
        sinaqs = Sinaqlar.objects.filter(is_active=True)
        for sinaq in sinaqs:
            if (sinaq.sinaq_nov == 'buraxilis10' and sinaq.counter == 0) or (sinaq.sinaq_nov == 'buraxilis11' and sinaq.counter == 0):
                all_text = sinaq.sinaq_sagird_cvb.split("\n")
                all_text = [self.replace_letters(x, self.letter_replacements) for x in all_text]
                right_answer = sinaq.sinaq_duzgun_cvb

                for row_number in range(len(all_text)):
                    ad = all_text[row_number][0:12]
                    soyad = all_text[row_number][13:25]
                    is_no = all_text[row_number][26:32]
                    sinif = all_text[row_number][33:34]
                    x_dil = all_text[row_number][43:44]
                    kod = all_text[row_number][45:48]
                    if sinif == 'a':
                        sinif = 10
                    elif sinif == 'b':
                        sinif = 11
                    f1_q = all_text[row_number][53:76]
                    f2_q = all_text[row_number][77:97]
                    f3_q = all_text[row_number][98:111]
                    f3_k_a = all_text[row_number][112:147]

                    if x_dil == "I":
                        d1_q = right_answer[0:23]
                    elif x_dil == "F":
                        d1_q = right_answer[98:121]
                    elif x_dil == "A":
                        d1_q = right_answer[123:146]
                    elif x_dil == "R":
                        d1_q = right_answer[148:171]
                    else:
                        d1_q = right_answer[0:23]
                    d2_q = right_answer[25:45]
                    d3_q = right_answer[47:60]
                    d3_k = right_answer[61:95]

                    if Buraxilis11.objects.filter(is_no=is_no, sinaq_no=sinaq.id):
                        person = Buraxilis11.objects.get(is_no=is_no, sinaq_no=sinaq.id)
                        person.aad = ad
                        person.soyad = soyad
                        person.sinif = sinif
                        person.kod = kod
                        person.xarici_dil = x_dil
                        person.f1_q = f1_q
                        person.f2_q = f2_q
                        person.f3_q = f3_q
                        person.f3_k_a = f3_k_a
                        person.d1_q = d1_q
                        person.d2_q = d2_q
                        person.d3_q = d3_q
                        person.d3_k = d3_k
                        person.save()
                    else:
                        person = Buraxilis11.objects.create(sinaq_no=sinaq.id, aad=ad, soyad=soyad, sinif=sinif,
                                                            is_no=is_no, kod=kod, xarici_dil=x_dil,
                                                            f1_q=f1_q, f2_q=f2_q, f3_q=f3_q, f3_k_a=f3_k_a, d1_q=d1_q,
                                                            d2_q=d2_q, d3_q=d3_q, d3_k=d3_k)
                        person.save()
                else:
                    new_counter = 1
                    return new_counter
            elif sinaq.sinaq_nov == 'buraxilis9' and sinaq.counter == 0:
                all_text = sinaq.sinaq_sagird_cvb.split("\n")
                all_text = [self.replace_letters(x, self.letter_replacements) for x in all_text]
                right_answer = sinaq.sinaq_duzgun_cvb

                for row_number in range(len(all_text)):
                    ad = all_text[row_number][0:12]
                    soyad = all_text[row_number][13:25]
                    is_no = all_text[row_number][26:32]
                    sinif = all_text[row_number][33:34]
                    x_dil = all_text[row_number][43:44]
                    kod = all_text[row_number][45:48]

                    f1_q = all_text[row_number][53:79]
                    f2_q = all_text[row_number][80:106]
                    f3_q = all_text[row_number][107:122]
                    f3_k_a = all_text[row_number][123:164]

                    if x_dil == "I":
                        d1_q = right_answer[0:26]
                    elif x_dil == "F":
                        d1_q = right_answer[116:142]
                    elif x_dil == "A":
                        d1_q = right_answer[144:170]
                    elif x_dil == "R":
                        d1_q = right_answer[172:198]
                    else:
                        d1_q = right_answer[0:26]

                    d2_q = right_answer[28:54]
                    d3_q = right_answer[56:71]
                    d3_k_a = right_answer[72:113]

                    if Buraxilis9.objects.filter(is_no=is_no, sinaq_no=sinaq.id):
                        person = Buraxilis9.objects.get(is_no=is_no, sinaq_no=sinaq.id)
                        person.aad = ad
                        person.soyad = soyad
                        person.sinif = sinif
                        person.xarici_dil = x_dil
                        person.kod = kod
                        person.f1_q = f1_q
                        person.f2_q = f2_q

istedad/templates/filiallar.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Filiallar {% endblock %}

{% block content %}

	<h1 style="text-align:center; padding:200px;">
		Tezliklə
	</h1>
	
{% endblock %}

istedad/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Əsas səhifə {% endblock %}

{% block content %}

	<aside id="fh5co-hero">
		<div class="flexslider">
			<ul class="slides">
				{% for esassehifes in esassehife %}
					{% if esassehifes.is_active %}
						<li style="background-image: url( {{esassehifes.sekil.url}} );">
							<div class="overlay-gradient"></div>
							<div class="container">
								<div class="row">
									<div class="col-md-8 col-md-offset-2 text-center slider-text">
										<div class="slider-text-inner">
											<h1>{{ esassehifes.basliq|safe }}</h1>
									    	<h2>{{ esassehifes.elave|safe }}</h2>
											<h2>{{ esassehifes.elave1|safe }}</h2>
										</div>
									</div>
								</div>
							</div>
						</li>
					{% endif %}
				{% endfor %}
		   	</ul>
	  	</div>
	</aside>

	<div id="fh5co-course">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>Xidmətlərimiz</h2>
				</div>
			</div>
			<div class="row">
				{% for kurslars in kurslar %}
					{% if kurslars.is_active %}
						<div class="col-md-6 animate-box">
							<div class="course">
								<a class="course-img" style="background-image: url({{ kurslars.sekil.url }});"></a>
								<div class="desc">
									<h3>{{kurslars.kurs_adi}}</h3>
									<p></p>
									<span><a href="{% url 'kurs_details' kurslars.slug %}" class="btn btn-primary btn-sm btn-course">Daha ətraflı</a></span>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>

	<div id="fh5co-counter" class="fh5co-counters" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="row">
						{% for saygacs in saygac %}
							{% if saygacs.is_active %}
								<div class="col-md-3 col-sm-6 text-center animate-box">
									<span class="icon"><i class="{{ saygacs.icon }}"></i></span>
									<span class="fh5co-counter js-counter" data-from="0" data-to="{{saygacs.cem}}" data-speed="{{saygacs.suret}}" data-refresh-interval="{{saygacs.interval}}"></span>
									<span class="fh5co-counter-label">{{saygacs.basliq}}</span>
								</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-blog">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>Xəbərlər</h2>
				</div>
			</div>
			<section class="articles">
				{% for tedbirss in tedbirler %}
					{% if tedbirss.is_active %}
						<article>
							<div class="article-wrapper">
								<figure>
									<img src="{{ tedbirss.sekil.url }}"/>
								</figure>
								<div class="article-body">
									<h2>{{ tedbirss.basliq }}</h2>
									<a href="{% url 'xeber_details' tedbirss.slug %}" class="read-more">Daha çox oxu <span class="sr-only"></span>
										<svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 20 20" fill="currentColor">
											<path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
										</svg>
									</a>
								</div>
							</div>
						</article>
					{% endif %}
				{% endfor %}
			</section>
		</div>
	</div>

	<div id="fh5co-testimonial" style="background-image: url({% static 'images/school.jpg' %});">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2><span>Şərhlər</span></h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<div class="row animate-box">
						<div class="owl-carousel owl-carousel-fullwidth">
							
						{% for serhlers in serhler %}
							{% if serhlers.is_active %}
								<div class="item">
									<div class="testimony-slide active text-center">
										<div class="user" style="background-image: url({{ serhlers.sekil.url }});"></div>
										<span>{{serhlers.ad_soyad}}<br><small>{{serhlers.basliq}}</small><br><small>{{serhlers.yuksek_netice}}</small></span>
										<blockquote>
											<p>&ldquo;{{serhlers.aciqlama}}&rdquo;</p>
										</blockquote>
									</div>
								</div>
							{% endif %}
						{% endfor %}
							
													
						</div>
					</div>
				</div>
			</div>			
		</div>
	</div>
	
	<div id="fh5co-register">
		<div class="overlay"></div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2 animate-box">
				<div class="date-counter text-center">
					<h2>Güzəştli qeydiyyat müddətimiz davam edir!</h2>
					<!--<div class="simply-countdown simply-countdown-one"></div>-->
					<p><strong>Tələsin!</strong></p>
					<p><a href="{% url 'qeydiyyat' %}" class="btn btn-primary btn-lg btn-reg">Qeydiyyatdan keç!</a></p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

istedad/templates/kurs-details.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{kurs.kurs_adi}} {% endblock %}

{% block content %}

	<div id="fh5co-about">
		<div class="container">
			<!--<div class="col-md-6 animate-box">
				<h2>{{ kurs.kurs_adi }}</h2>				
			</div>-->
		</div>
		<div class="container">
			<p>{{ kurs.genis_melumat|safe }}</p>
		</div>	
	</div>

{% endblock %}

istedad/templates/kurslar.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Xidmətlərimiz {% endblock %}

{% block content %}

	<div id="fh5co-course">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>Xidmətlərimiz</h2>
				</div>
			</div>
			<div class="row">
				{% for kurslars in kurslar %}
					{% if kurslars.is_active %}
						<div class="col-md-6 animate-box">
							<div class="course">
								<a class="course-img" style="background-image: url({{ kurslars.sekil.url }});"></a>
								<div class="desc">
									<h3>{{kurslars.kurs_adi}}</h3>
									<p></p>
									<span><a href="{% url 'kurs_details' kurslars.slug %}" class="btn btn-primary btn-sm btn-course">Daha ətraflı</a></span>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

istedad/templates/media.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Media {% endblock %}

{% block css %}
	#formid{
		display:table;
		margin:auto;
	}
	label{
		display:inline-block;
		text-transform:uppercase;
		color:#fff;
		background:#c0392b;
		text-align:center;
		padding:15px 40px;
		letter-spacing:1.5px;
		user-select:none;
		cursor:pointer;
	}
	input[type="file"]{
		display:none;
	}
{% endblock %}

{% block content %}
	{%if user.is_authenticated%}
		<div class="row">
			<form id="formid" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<label for="id_sekil">Şəkil:</label>
				<input type="file" name="sekil" multiple required id="id_sekil">
				<button type="submit">Yüklə</button>
			</form>
		</div>
	{%endif%}
	
	<div id="fh5co-gallery" class="fh5co-bg-section">
	<div class="row text-center"><h2><span>Galareya</span></h2></div>
		{% for medias in media %}
			{% if medias.is_active %}

				<div class="row col-md-3 col-padded">
					<h2 class="text-center col-padded">{{ medias.sekil_adi }}</h2><a href="#" class="gallery" style="background-image: url({{ medias.sekil.url }});" ></a>
				</div>
			
			{% endif %}
		{% endfor %}
	</div>

{% endblock %}

istedad/templates/muellimler.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Müəllim heyəti {% endblock %}

{% block content %}
	
	<div id="fh5co-staff">
		<div class="container">
			<div class="row">
				
				{% for muellimss in muellim %}
					{% if muellimss.is_active %}
						<div class="col-md-3 text-center">
							<div class="staff">
								<div class="staff-img" style="background-image: url({{ muellimss.sekil.url }});"></div>
								<span>{{muellimss.fenn}}</span>
								<h3>{{muellimss.ad}}</h3>
								<p>{{muellimss.aciqlama|safe}}</p>
							</div>
						</div>
					{% endif %}
				{% endfor %}
					
								
			</div>
		</div>
	</div>
{% endblock %}

istedad/templates/sinaq_details.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Sınaqlar {% endblock %}

{% block content %}

	<div id="fh5co-pricing" class="fh5co-bg-section">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
					<h2>Sınaq nəticələri</h2>
				</div>

				<div class="col-md-6 animate-box">
					<form action="{% url 'sinaqcavab' %}" method="get">
						<div class="row form-group">
							<div class="col-md-12">
								<input type="search" name="search" placeholder="İş nömrəsi">
								<input type="hidden" name="id" value="{{sinaq.id}}" readonly>
							</div>
						</div>
						
						<div class="form-group">
							<input type="submit" value="Göstər" class="btn btn-success">
						</div>
					</form>
				</div>
				<div class="col-md-6 animate-box">
					{% if user.is_authenticated %}
						<form action="{% url 'adminsinaqcavab' %}" method="get">
							<div class="row form-group">
								<div class="col-md-12">
									<strong>Cavab kağızlarına bax</strong>
									<input type="hidden" name="id" value="{{sinaq.id}}" readonly>
									<input type="hidden" name="sinaqtipi" value="Karne" readonly>
									<input type="submit" value="Göstər" class="btn btn-success">
								</div>
							</div>
							
						</form>
						<form action="{% url 'adminsinaqcavab' %}" method="get">
							<div class="row form-group">
								<div class="col-md-12">
									<strong>Siyahı şəklində bax</strong>
									<input type="hidden" name="id" value="{{sinaq.id}}" readonly>
									<input type="hidden" name="sinaqtipi" value="Siyahi" readonly>
									<input type="submit" value="Göstər" class="btn btn-success">
								</div>
							</div>
						</form>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

{% endblock %}

istedad/templates/sinaqnetice.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Sınaqlar {% endblock %}

{% block content %}

    <div id="fh5co-gallery" class="fh5co-bg-section">
        <div class="row text-center"><h2><span>Sınaqlar</span></h2></div>
            {% for sinaq in sinaqs %}
                {% if sinaq.is_active or user.is_authenticated %}

                    <div class="row col-md-3 col-padded">
                        <h2 class="text-center col-padded">{{ sinaq.sinaq_adi }}</h2><a href="{% url 'sinaq_details' sinaq.id %}" class="gallery" style="background-image: url({{ sinaq.sinaq_sekil.url }});" ></a>
                    </div>

                {% endif %}
            {% endfor %}
    </div>
	
{% endblock %}

istedad/templates/struktur.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Struktur {% endblock %}

{% block content %}


	<div id="fh5co-staff">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<div class="staff">
						<div class="staff-img" style="background-image: url({% static 'images/rektor.jpg' %}); height: 650px;">
						</div>
						<span>İstedad XXI əsr MMC-nin təsisçisi</span>
						<h3>Elbrus İsayev</h3>
						<p>Tarix üzrə fəlsəfə doktoru, dosent</p>
					</div>
				</div>
				{% for strukturs in struktur %}
					{% if strukturs.is_active %}
						<div class="col-md-4 text-center">
							<div class="staff">
								<div class="staff-img" style="background-image: url({{ strukturs.sekil.url }});">
								</div>
								<span>{{ strukturs.vezife }}</span>
								<h3>{{ strukturs.ad_soyad }}</h3>
								<p>{{ strukturs.elave }}</p>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

istedad/templates/tedbirler.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Xəbərlər {% endblock %}

{% block content %}
	<div id="fh5co-blog">
		<div class="container">
			<section class="articles">
				{% for tedbirss in tedbirler %}
					{% if tedbirss.is_active %}
						<article>
							<div class="article-wrapper">
								<figure>
									<img src="{{ tedbirss.sekil.url }}"/>
								</figure>
								<div class="article-body">
									<h2>{{ tedbirss.basliq }}</h2>
									<!--<p>{{ tedbirss.aciqlama|safe }}</p>-->
									<a href="{% url 'xeber_details' tedbirss.slug %}" class="read-more">Daha çox oxu <span class="sr-only"></span>
										<svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 20 20" fill="currentColor">
											<path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
										</svg>
									</a>
								</div>
							</div>
						</article>
					{% endif %}
				{% endfor %}
			</section>
		</div>
	</div>
{% endblock %}

istedad/templates/xeber-details.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{xeber.basliq}} {% endblock %}

{% block content %}

	<div id="fh5co-about">
		<div class="container">
			<h1>{{xeber.basliq}}</h1>
			<h3>{{xeber.tarix}}</h3>
			<img id="xeber" src="{{ xeber.sekil.url }}"/>
			{{ xeber.aciqlama|safe }}
		</div>	
	</div>

{% endblock %} 